export enum CompanyMemberRole {
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
  RESELLER = "RESELLER",
}

export enum RouteAction {
  ALLOW = "ALLOW",
  REDIRECT_LOGIN = "REDIRECT_LOGIN",
  REDIRECT_DASHBOARD = "REDIRECT_DASHBOARD",
  REDIRECT_ADMIN = "REDIRECT_ADMIN",
  FORBIDDEN = "FORBIDDEN",
}
